name: Lint & Test

on:
  pull_request:
  push:
    branches: [develop, base, sensor]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - uses: pre-commit/action@v3.0.0

  validate_hacs:
    name: "HACS"
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v6"
      - name: HACS Action
        uses: "hacs/action@22.5.0"
        with:
          category: "integration"

  validate_hassfest:
    name: "Hassfest"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v6"
      - uses: "home-assistant/actions/hassfest@master"

  test:
    runs-on: "ubuntu-latest"
    name: "Tests (Python ${{ matrix.python-version }})"
    strategy:
      matrix:
        python-version: ["3.13", "3.14"]
    steps:
      - name: Check out code from GitHub
        uses: "actions/checkout@v6"
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Run tests
        run: |
          uv run pytest \
            -qq \
            --timeout=9 \
            --durations=10 \
            -n auto \
            --cov custom_components.ttlock \
            --cov-report=xml \
            -o console_output_style=count \
            -p no:sugar \
            --cov --junitxml=junit.xml -o junit_family=legacy \
            tests
      - name: Upload coverage reports to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
